Repository sebamarynissen/simtropolis-channel, pull requests merged in 2025-02, with the labels that each got.

#128 metadata: add `nique:modular-noise-barriers`
  src/yaml/nique/29875-modular-noise-barriers-brown.yaml
Labels: package

#129 metadata: split `simmer2:center-pivot-irrigation-fields`
  src/yaml/simmer2/32701-center-pivot-irrigation-fields.yaml
Labels: package

#132 Add Roe99's Content
  src/yaml/roe99/23111-grandiosedometower.yaml
  src/yaml/roe99/23112-grandiosedomeg7.yaml
  src/yaml/roe99/23300-state-fair-market.yaml
  src/yaml/roe99/23406-pasar-tanah-abang.yaml
  src/yaml/roe99/23432-elsha-condoz.yaml
  src/yaml/roe99/23478-menara-imperium.yaml
  src/yaml/roe99/23527-gkbi-tower.yaml
  src/yaml/roe99/23567-talavera-office-park.yaml
  src/yaml/roe99/23622-sentra-mulia-tower.yaml
  src/yaml/roe99/23667-menara-batavia-update.yaml
  src/yaml/roe99/23838-the-peak-part1.yaml
  src/yaml/roe99/23839-da-vinci-update.yaml
  src/yaml/roe99/23849-the-peak-final.yaml
  src/yaml/roe99/24213-transjakarta-busway.yaml
  src/yaml/roe99/24215-soeman-hs-riau-library.yaml
  src/yaml/roe99/24216-repaint-maxis-ferry.yaml
  src/yaml/roe99/24217-elsha-watermod.yaml
  src/yaml/roe99/24218-garuda-indonesia-airline.yaml
  src/yaml/roe99/24219-singapore-airlines-747-400.yaml
  src/yaml/roe99/24221-thai-airlines-a340-600-and-a330-200.yaml
  src/yaml/roe99/24222-malaysia-airlines-and-airasia-darkblue.yaml
  src/yaml/roe99/24412-regatta.yaml
  src/yaml/roe99/26196-bundaran-hi.yaml
  src/yaml/roe99/26200-wisma46-v2.yaml
  src/yaml/roe99/26364-area-24.yaml
  src/yaml/roe99/26406-equity-tower.yaml
  src/yaml/roe99/26505-mnc-tower.yaml
  src/yaml/roe99/32448-monas-monument.yaml
Labels: package

#134 metadata: add PBGV103's content
  permissions.yaml
  src/yaml/pbgv103/22870-885-3rd-avenue.yaml
  src/yaml/pbgv103/22909-us-armed-forces-recruiting-station.yaml
  src/yaml/pbgv103/23307-570-560-lexington-v2.yaml
  src/yaml/pbgv103/24301-mutual-of-america-building.yaml
  src/yaml/pbgv103/26060-425-lexington-avenue.yaml
Labels: package

#135 metadata: add golf courses
  src/yaml/doctorgonzo/2643-artgolf-golf-course.yaml
  src/yaml/peg/22701-ppond-terrain-props-pack-1.yaml
  src/yaml/sim-idiot/3228-sc-golf-pack.yaml
  src/yaml/skimbo/25700-sc4-golf-pack.yaml
Labels: package

#133 metadata: add VIP Team's content
  permissions.yaml
  scripts/sc4d.js
  src/yaml/vip/26807-aubracwallmmp.yaml
  src/yaml/vip/26964-orange-an-der-alster-1.yaml
  src/yaml/vip/27080-vnaoned-european-road-signage-frenchtype-v2.yaml
  src/yaml/vip/28498-snow-theme-pack-vol1.yaml
  src/yaml/vip/28545-vineyard.yaml
  src/yaml/vip/28847-orange-pinus-nigra.yaml
  src/yaml/vip/28848-orange-cupressus.yaml
Labels: package

#136 Add various packages
  permissions.yaml
  src/yaml/joerg/1844-sim-high.yaml
  src/yaml/joerg/1976-golf-pack.yaml
  src/yaml/joerg/2431-sim-metro-life-arena.yaml
  src/yaml/joerg/811-the-rich-guys-place.yaml
  src/yaml/shadow-assassin/15363-cycleways-basic-pack.yaml
  src/yaml/shadow-assassin/15534-cycleways-expansion-pack-1.yaml
  src/yaml/timo/11426-stade-de-france-v1.yaml
  src/yaml/timo/11770-stade-de-france-v3-rugby-stadium.yaml
Labels: package

#137 Add various mmp packs
  permissions.yaml
  src/yaml/goldiva/13067-mayor-mode-tropical-tree-set.yaml
  src/yaml/goldiva/13068-mayor-mode-tropical-sea-set.yaml
  src/yaml/goldiva/3355-water-taxi-station-wbus-stop-new-water-taxi.yaml
  src/yaml/kergelen/27973-mmp-mediterranean-cp-trees-krg-selection.yaml
  src/yaml/peg/21661-ppond-kit.yaml
Labels: package

#146 fix: properly quote boolean-like values
  actions/fetch/stylize-doc.js
  actions/fetch/test/integration-test.js
Labels: bug

#147 fix: fix accidental double quoting
  actions/fetch/stylize-doc.js
  actions/fetch/test/integration-test.js
Labels: bug

#163 Update 36707-universal-sea-level-mod.yaml
  src/yaml/smf-16/36707-universal-sea-level-mod.yaml
Labels: bug, package

#164 feat: update to STEX api v2
  .github/workflows/add-packages.yaml
  actions/fetch/api-to-metadata.js
  actions/fetch/check-previous-version.js
  actions/fetch/complete-metadata.js
  actions/fetch/downloader.js
  actions/fetch/fetch-all.js
  actions/fetch/fetch.js
  actions/fetch/generate-variants.js
  actions/fetch/handle-upload.js
  actions/fetch/parse-dependencies.js
  actions/fetch/parse-description.js
  actions/fetch/patch-metadata.js
  actions/fetch/permissions.js
  actions/fetch/scrape.js
  actions/fetch/split-package.js
  actions/fetch/test/api-to-metadata-test.js
  actions/fetch/test/descriptor-to-subfolder-test.js
  actions/fetch/test/expand-variants-test.js
  actions/fetch/test/faker.js
  actions/fetch/test/integration-test.js
  actions/fetch/test/patch-metadata-test.js
  actions/fetch/test/split-package-test.js
  scripts/manual-add.js
Labels: feature

#169 metadata: add more of Peg's content
  actions/fetch/handle-upload.js
  scripts/standard-deps.js
  src/yaml/peg/10897-rtk3-recreational-style.yaml
  src/yaml/peg/10934-rtk3-rec-addon1.yaml
  src/yaml/peg/11054-seasonal-trail-parks.yaml
  src/yaml/peg/11334-observation-tower.yaml
  src/yaml/peg/11775-cdk-rec-prop-pack-1.yaml
  src/yaml/peg/12007-cdk-oww-development-pack-vol1.yaml
  src/yaml/peg/13059-trail-park-fountain-plaza.yaml
  src/yaml/peg/14026-mtp-random-pine-forest.yaml
  src/yaml/peg/14055-mtp-mountain-trail-rail-crossing.yaml
  src/yaml/peg/14058-mtp-mountain-trail-fire-circle.yaml
  src/yaml/peg/14097-mtp-forest-pack-1.yaml
  src/yaml/peg/14107-mtp-low-wealth-growable-res-cabins.yaml
  src/yaml/peg/14158-mtp-high-wealth-growable-res-lodges.yaml
  src/yaml/peg/14241-mtp-urgent-care-clinic.yaml
  src/yaml/peg/14250-mtp-old-school-house.yaml
  src/yaml/peg/14379-mtp-santas-village-alternate-audio.yaml
  src/yaml/peg/14586-mtp-no-roadway-junk-mod.yaml
  src/yaml/peg/14620-mtp-rural-roadways-mod.yaml
  src/yaml/peg/14809-mtp-scenic-views.yaml
  src/yaml/peg/14810-mtp-sway-bridge.yaml
  src/yaml/peg/15794-mtp-res-replacement-mod.yaml
  src/yaml/peg/30651-santas-village.yaml
  src/yaml/peg/4515-mtp-seasonal-woods.yaml
  src/yaml/peg/4523-pine-forest.yaml
  src/yaml/peg/4526-mtp-random-woods.yaml
  src/yaml/peg/4530-rtk3-watertreatment-plant.yaml
Labels: package

#170 metadata: add anotn's content
  actions/fetch/fetch.js
  permissions.yaml
  scripts/manual-add.js
  scripts/sc4d.js
  src/yaml/anotn/26685-mott-haven-corner.yaml
  src/yaml/anotn/27039-the-aurora.yaml
  src/yaml/anotn/27274-augustenborg-houses.yaml
  src/yaml/anotn/28222-345-seventh-avenue.yaml
Labels: package

#171 metadata: add `11241036:vip-trees-as-props`
  src/yaml/11241036/33702-vip-trees-as-props.yaml
Labels: package

#121 Add Kellydale2003's content
  src/yaml/kellydale2003/19735-atlantic-records-construction.yaml
  src/yaml/kellydale2003/26805-kingston-developments-ltd-under-construction.yaml
  src/yaml/kellydale2003/26817-james-richardson-and-sons-ltd-hq.yaml
  src/yaml/kellydale2003/27269-centre-place-bank-of-moscow.yaml
  src/yaml/kellydale2003/27565-linda-swampy-medical-centre.yaml
  src/yaml/kellydale2003/28333-absolute-city-centre-absolute-world-one.yaml
  src/yaml/kellydale2003/28347-1001-yonge-st-offices-and-library.yaml
  src/yaml/kellydale2003/28348-vohcem-condominiums.yaml
  src/yaml/kellydale2003/28361-eicosakis-biology-research-centre.yaml
  src/yaml/kellydale2003/29041-11-king-street-west.yaml
  src/yaml/kellydale2003/29054-u-of-w-science-complex.yaml
  src/yaml/kellydale2003/29061-paris-building.yaml
  src/yaml/kellydale2003/30475-bay-adelaide-centre-west.yaml
  src/yaml/kellydale2003/31862-ritz-carlton-toronto.yaml
  src/yaml/kellydale2003/31868-palais-garnier-remastered.yaml
  src/yaml/kellydale2003/31873-eighth-avenue-place-east-tower.yaml
  src/yaml/kellydale2003/32474-royal-bank-of-sims.yaml
  src/yaml/kellydale2003/32500-scotia-plaza-toronto.yaml
  src/yaml/kellydale2003/32614-the-bow-calgary-canada.yaml
  src/yaml/kellydale2003/32618-300-main-residences-winnipeg-canada.yaml
  src/yaml/kellydale2003/32691-cn-tower-new-years-day-version.yaml
  src/yaml/kellydale2003/32722-royal-bank-plaza-toronto.yaml
  src/yaml/kellydale2003/32725-four-seasons-hotel-and-residences-toronto.yaml
  src/yaml/kellydale2003/34097-apple-hq-beta-version.yaml
Labels: package

#138 Add Wallibuk's content
  scripts/sc4d.js
  src/yaml/wallibuk/28654-evanielick-kostol-v-stitniku.yaml
  src/yaml/wallibuk/28656-slum-set.yaml
  src/yaml/wallibuk/28669-dom-svateho-martina.yaml
  src/yaml/wallibuk/28700-rural-churches-in-gemer.yaml
  src/yaml/wallibuk/28739-favela.yaml
  src/yaml/wallibuk/28840-slovak-hungarian-transylvanian-rural-houses.yaml
  src/yaml/wallibuk/28909-czechoslovak-socialist-houses.yaml
  src/yaml/wallibuk/28944-spisska-kapitula.yaml
  src/yaml/wallibuk/28945-oravsky-hrad.yaml
  src/yaml/wallibuk/28967-novy-zamok.yaml
  src/yaml/wallibuk/28979-stary-dom.yaml
  src/yaml/wallibuk/28986-nam-majstra-pavla-c-27-a-28.yaml
  src/yaml/wallibuk/28997-hlavna-ulica-2985-86-presov.yaml
  src/yaml/wallibuk/29011-slovenske-domy.yaml
  src/yaml/wallibuk/29137-latino-house.yaml
  src/yaml/wallibuk/29414-roznavska-radnica.yaml
  src/yaml/wallibuk/29415-obchod-t-v-rimavskej-sobote.yaml
  src/yaml/wallibuk/29553-slovak-medieval-townhouses-set.yaml
  src/yaml/wallibuk/29588-kostol-sv-egidia-bardejov-slovakia.yaml
  src/yaml/wallibuk/29622-domy-z-blavy.yaml
  src/yaml/wallibuk/30038-stare-domy.yaml
  src/yaml/wallibuk/30079-town-gate.yaml
  src/yaml/wallibuk/30117-slovak-hungarian-smalltown.yaml
  src/yaml/wallibuk/30170-kostoly-na-gemeri.yaml
  src/yaml/wallibuk/30944-south-american-houses-pack.yaml
  src/yaml/wallibuk/31037-gelati-monastery-georgia.yaml
  src/yaml/wallibuk/32667-fort-gross-friedrichsburg.yaml
  src/yaml/wallibuk/33628-lagos-slum-houses.yaml
  src/yaml/wallibuk/33629-stadhuis-batavia.yaml
Labels: package

#178 metadata: promoto `peg:one-flag-many-nations` to default channel
  src/yaml/peg/27711-one-flag-many-nations-mod.yaml
Labels: package

#177 Add on001222's content
  src/yaml/on001222/23471-the-carson-building.yaml
  src/yaml/on001222/23563-ptt-hq.yaml
  src/yaml/on001222/23623-townhouse-pack.yaml
  src/yaml/on001222/23717-ajinomoto-thailand-company.yaml
  src/yaml/on001222/23816-suparat-tower-1.yaml
  src/yaml/on001222/23817-thailand-bus-stop.yaml
  src/yaml/on001222/23846-suparat-condominium-and-hotel.yaml
  src/yaml/on001222/23943-lumpinee-park-condominium.yaml
  src/yaml/on001222/23946-bangkok-city-tower.yaml
  src/yaml/on001222/24038-phrapathomchedee.yaml
  src/yaml/on001222/24145-thai-wah-tower-2-banyan-tree-bangkok-hotel.yaml
  src/yaml/on001222/24198-itf-silom-palace.yaml
  src/yaml/on001222/24276-empire-tower.yaml
  src/yaml/on001222/24508-silom-suite-condominium.yaml
  src/yaml/on001222/24542-deutsche-bank-place.yaml
  src/yaml/on001222/24816-thai-wah-tower-1v2.yaml
  src/yaml/on001222/24843-vanit-tower-2.yaml
  src/yaml/on001222/24896-rasa-tower-1-and-2-v2.yaml
  src/yaml/on001222/24912-thai-farmer-bank-kasikorn-thai-bank.yaml
  src/yaml/on001222/24917-thai-farmer-bank-kasikorn-thai-bank-v2.yaml
  src/yaml/on001222/25071-millenium-residance-1-2-3-4.yaml
  src/yaml/on001222/25133-arnoma-hotel-bangkok.yaml
  src/yaml/on001222/25232-las-coulinas-condo.yaml
  src/yaml/on001222/27060-asia-center.yaml
  src/yaml/on001222/27131-sathorn-thani-complex-v2.yaml
  src/yaml/on001222/27263-bangkok-insurance-pcl.yaml
  src/yaml/on001222/27860-baiyoke-sky-hotel.yaml
  src/yaml/on001222/27965-q-house-lumpini.yaml
  src/yaml/on001222/28020-sme-bank-tower.yaml
  src/yaml/on001222/28369-the-met-v-2-5.yaml
  src/yaml/on001222/28509-abdulrahim-place.yaml
  src/yaml/on001222/28525-regent-house.yaml
  src/yaml/on001222/28557-rose-tower.yaml
  src/yaml/on001222/28591-grand-view-apartment.yaml
  src/yaml/on001222/28646-orakarn-building.yaml
  src/yaml/on001222/28935-lotus-temple-bahai-house.yaml
  src/yaml/on001222/29093-royal-maneeya-renaissance-bangkok.yaml
  src/yaml/on001222/29632-park-ventures.yaml
  src/yaml/on001222/29886-mahanakhon-condo.yaml
  src/yaml/on001222/30947-ocean-tower-2.yaml
  src/yaml/on001222/31331-amari-watergate-hotel-bangkok.yaml
  src/yaml/on001222/31397-interchange-21.yaml
  src/yaml/on001222/33484-mobicom-buiding.yaml
  src/yaml/on001222/33485-thai-style-building.yaml
  src/yaml/on001222/33498-nara9-condominium.yaml
  src/yaml/on001222/33521-tepdusit-company.yaml
  src/yaml/on001222/34053-skulthai-surawong-tower.yaml
  src/yaml/on001222/34069-jc-kevin-bangkok.yaml
  src/yaml/on001222/34714-small-office.yaml
  src/yaml/on001222/34718-bangna-apartment.yaml
  src/yaml/on001222/34721-bansuanpetch-condominium.yaml
  src/yaml/on001222/34727-tmb-bank-by-userlake.yaml
  src/yaml/on001222/34736-the-xxxix-condominium.yaml
  src/yaml/on001222/34832-forward-tower.yaml
Labels: package
