Repository sebamarynissen/simtropolis-channel, pull requests merged in 2025-01, with the labels that each got.

#57 feat: automatically detect growable lots with cam variants
  actions/fetch/complete-metadata.js
  actions/fetch/detect-growables.js
  actions/fetch/downloader.js
  actions/fetch/fetch-all.js
  actions/fetch/handle-upload.js
  actions/fetch/symbols.js
  actions/fetch/test/detect-growables-test.js
  actions/fetch/test/detect-growables/growable.SC4Desc
  actions/fetch/test/detect-growables/growable.SC4Lot
  actions/fetch/test/detect-growables/ploppable.SC4Lot
  actions/fetch/test/expand-variants-test.js
  actions/fetch/test/integration-test.js
  package-lock.json
  package.json
Labels: enhancement

#58 metadata: add WannGLondon's content
  actions/fetch/api-to-metadata.js
  actions/fetch/complete-metadata.js
  actions/fetch/test/api-to-metadata-test.js
  actions/fetch/test/integration-test.js
  src/yaml/wannglondon/34082-old-mediterranean-pack.yaml
  src/yaml/wannglondon/34088-mediterranean-flats.yaml
  src/yaml/wannglondon/34117-mediterranean-flats-corner-a.yaml
  src/yaml/wannglondon/34119-mediterranean-flats-corner-b.yaml
  src/yaml/wannglondon/34150-wanng-paris-pack-1-r.yaml
  src/yaml/wannglondon/34169-wanng-paris-pack-2-r.yaml
  src/yaml/wannglondon/34172-paris-batiment-9-left-corner.yaml
  src/yaml/wannglondon/34175-paris-batiment-10-right-corner.yaml
  src/yaml/wannglondon/34214-wanng-paris-pack-3-r.yaml
  src/yaml/wannglondon/34268-wanng-hotel-particulier-pack.yaml
  src/yaml/wannglondon/34297-paris-batiment-15.yaml
  src/yaml/wannglondon/34318-paris-batiments-16-18.yaml
  src/yaml/wannglondon/34416-retro-tower-1.yaml
  src/yaml/wannglondon/34427-london-flats-1.yaml
  src/yaml/wannglondon/34608-mediterranean-flats-2.yaml
  src/yaml/wannglondon/34715-mediterranean-pack-1.yaml
  src/yaml/wannglondon/34770-mediterranean-buildings-13-14.yaml
  src/yaml/wannglondon/34835-mediterranean-pack-2.yaml
  src/yaml/wannglondon/34843-paris-batiments-20-21.yaml
  src/yaml/wannglondon/34876-mediterranean-pack-3.yaml
  src/yaml/wannglondon/35017-london-building-1.yaml
  src/yaml/wannglondon/35022-french-hospital.yaml
  src/yaml/wannglondon/35301-haunted-mansion.yaml
  src/yaml/wannglondon/35555-paris-batiments-32-33.yaml
  src/yaml/wannglondon/35563-paris-batiment-34.yaml
  src/yaml/wannglondon/35566-medit-bldg-50.yaml
  src/yaml/wannglondon/35568-london-flats-5.yaml
  src/yaml/wannglondon/35571-london-flats-3.yaml
  src/yaml/wannglondon/35575-grand-arch.yaml
  src/yaml/wannglondon/35582-wanng-random-pack-1.yaml
  src/yaml/wannglondon/35632-new-york-pack-1.yaml
  src/yaml/wannglondon/35650-ny-building-10.yaml
  src/yaml/wannglondon/35762-paris-park-hyatt-vendome.yaml
  src/yaml/wannglondon/35885-the-home-alone-house.yaml
  src/yaml/wannglondon/36086-ny-building-11.yaml
  src/yaml/wannglondon/36087-ny-building-12.yaml
  src/yaml/wannglondon/36165-mairie.yaml
  src/yaml/wannglondon/36213-medit-bldg-59.yaml
  src/yaml/wannglondon/36214-ancient-ampitheater.yaml
  src/yaml/wannglondon/36253-tower-4.yaml
  src/yaml/wannglondon/36254-tiki-tims.yaml
  src/yaml/wannglondon/36300-los-angeles-home-pack-1.yaml
  src/yaml/wannglondon/36385-san-francisco-buildings-1.yaml
  src/yaml/wannglondon/36482-raven-hollow-inn.yaml
  src/yaml/wannglondon/36505-american-rowhomes-pack-1.yaml
  src/yaml/wannglondon/36523-american-rowhome-8.yaml
  src/yaml/wannglondon/36567-mid-century-modern-homes-pack.yaml
  src/yaml/wannglondon/36570-apartments-2.yaml
  src/yaml/wannglondon/36575-apartments-3.yaml
  src/yaml/wannglondon/36576-tulum-homes.yaml
  src/yaml/wannglondon/36578-vintage-sign-prop-pack.yaml
  src/yaml/wannglondon/36621-grand-mediterranean-hotels.yaml
Labels: package

#62 Add fribe's content
  src/yaml/fribe/27014-nighthawks-stadium.yaml
  src/yaml/fribe/27255-bighorn-bowl.yaml
  src/yaml/fribe/27371-elmer-s-nursery.yaml
  src/yaml/fribe/27389-bowman-gray-stadium.yaml
  src/yaml/fribe/27586-arctic-circle-ice-cream.yaml
  src/yaml/fribe/27657-talbot-speedway.yaml
  src/yaml/fribe/27853-creek-park-stadium.yaml
  src/yaml/fribe/27899-43-brothers-pizza.yaml
  src/yaml/fribe/28019-hemphill-place.yaml
  src/yaml/fribe/28138-royal-farms.yaml
  src/yaml/fribe/28499-back-river-wastewater-treatment-plant.yaml
  src/yaml/fribe/28529-telegraph-inn.yaml
  src/yaml/fribe/28601-brewer-stadium.yaml
  src/yaml/fribe/28602-brewer-stadium-canada-edition.yaml
  src/yaml/fribe/28664-mallow-park.yaml
  src/yaml/fribe/28736-beachcomber-tower.yaml
Labels: package

#63 metadata: add modular amusement park pack
  src/yaml/aldara6166/17557-modular-amusement-park-pack-essentials.yaml
  src/yaml/aldara6166/17558-modular-amusement-park-pack-classic-rides.yaml
  src/yaml/aldara6166/17559-modular-amusement-park-pack-modern-rides.yaml
  src/yaml/aldara6166/17560-modular-amusement-park-pack-roller-coasters.yaml
Labels: package

#64 Add `deadwoods:highway-walls`
  permissions.yaml
  src/yaml/deadwoods/16556-highway-walls.yaml
Labels: package

#68 feat: tag known GitHub users if linting fails
  actions/create-prs/create-prs.js
  actions/fetch/handle-upload.js
  actions/fetch/permissions.js
  actions/fetch/test/integration-test.js
  permissions.yaml
Labels: feature

#69 fix: handle removed files within a PR
  actions/create-prs/create-prs.js
Labels: bug

#70 fix: handle removed files within a PR
  actions/create-prs/create-prs.js
Labels: bug

#71 fix: Github usernames are not logged in PRs
  actions/fetch/permissions.js
  actions/fetch/test/integration-test.js
Labels: bug

#72 fix: handle changing filenames within PR
  actions/create-prs/create-prs.js
  actions/fetch/handle-upload.js
  actions/fetch/test/integration-test.js
  package-lock.json
  package.json
Labels: bug

#73 feat: improve PR generation
  actions/create-prs/create-prs.js
  actions/fetch/api-to-metadata.js
  actions/fetch/handle-upload.js
  actions/fetch/permissions.js
  actions/fetch/test/api-to-metadata-test.js
  actions/fetch/test/integration-test.js
Labels: feature, actions

#74 fix: handle uploads without files
  actions/fetch/handle-upload.js
  actions/fetch/test/integration-test.js
Labels: bug

#75 feat: support `metadata.yaml` in nested folders
  README.md
  actions/create-prs/create-prs.js
  actions/fetch/downloader.js
  actions/fetch/handle-upload.js
  actions/fetch/test/integration-test.js
Labels: enhancement

#37 feat: automatically generate checksums for dll's
  README.md
  actions/fetch/downloader.js
  actions/fetch/handle-upload.js
  actions/fetch/patch-metadata.js
  actions/fetch/test/integration-test.js
  actions/fetch/test/patch-metadata-test.js
  lint-config.yaml
Labels: feature

#77 feat: implement script to manually add contributions
  package-lock.json
  package.json
  scripts/manual-add.js
  scripts/parse-dependencies.js
  scripts/sc4d.js
  scripts/tsc.js
Labels: feature

#78 feat: add script for pruning dependencies
  package-lock.json
  package.json
  scripts/manual-add.js
  scripts/prune.js
  scripts/sc4pac.js
  scripts/standard-deps.js
  scripts/symlink.js
  scripts/traverse-yaml.js
  src/yaml/ceafus-88/35441-dollar-general.yaml
Labels: feature

#79 metadata: add I. Lostalim's content
  permissions.yaml
  src/yaml/blunder/28538-the-reflectoblob.yaml
  src/yaml/der-gammler/21416-riverbed-and-beach.yaml
  src/yaml/der-gammler/21594-small-fachwerk-houses.yaml
  src/yaml/der-gammler/27199-plopwater-pack-1.yaml
  src/yaml/i-lostalim/26058-super-china-buffet.yaml
  src/yaml/i-lostalim/26061-lenny-s-fast-food.yaml
  src/yaml/i-lostalim/26063-prop-hedge-collection.yaml
  src/yaml/i-lostalim/26081-prop-hedge-collection-volume-2.yaml
  src/yaml/i-lostalim/26201-chung-s-chinese-food.yaml
  src/yaml/i-lostalim/26727-stoneridge-apartments.yaml
  src/yaml/i-lostalim/27047-prop-hedge-collection-3.yaml
  src/yaml/i-lostalim/27402-modular-house-set.yaml
  src/yaml/i-lostalim/27403-colonial-house.yaml
  src/yaml/i-lostalim/27459-brickside-elementary-school.yaml
  src/yaml/i-lostalim/27460-five-guys-burgers-and-fries.yaml
  src/yaml/i-lostalim/27461-northfield-bank.yaml
  src/yaml/i-lostalim/27478-treble-plaza.yaml
  src/yaml/i-lostalim/27487-bass-clef-park.yaml
  src/yaml/i-lostalim/27488-parameter-software.yaml
  src/yaml/i-lostalim/27495-c-clef-plaza.yaml
  src/yaml/i-lostalim/27496-culver-s.yaml
  src/yaml/i-lostalim/27516-european-townhouse.yaml
  src/yaml/i-lostalim/27517-modern-row-house-set.yaml
  src/yaml/i-lostalim/27577-benton-brothers-group-insurance-ltd.yaml
  src/yaml/i-lostalim/27612-simcity-3000-base-textures.yaml
  src/yaml/i-lostalim/27620-pavilion-apartments.yaml
  src/yaml/i-lostalim/27640-oceanside-condos.yaml
  src/yaml/i-lostalim/27643-fillmore-estate.yaml
  src/yaml/i-lostalim/27650-brickside-lofts.yaml
  src/yaml/i-lostalim/27651-brick-heights.yaml
  src/yaml/i-lostalim/27684-lostalim-vascular.yaml
  src/yaml/i-lostalim/27694-aquarium-condos.yaml
  src/yaml/i-lostalim/27732-larry-s-law-firm.yaml
  src/yaml/i-lostalim/27737-sue-s-pet-castle.yaml
  src/yaml/i-lostalim/27815-corporations-pack.yaml
  src/yaml/i-lostalim/27901-234-north-main.yaml
  src/yaml/i-lostalim/27958-cascade-center.yaml
  src/yaml/i-lostalim/27959-stanley-towers.yaml
  src/yaml/i-lostalim/28219-hydroponics-co.yaml
  src/yaml/i-lostalim/34363-cadenza-building.yaml
  src/yaml/i-lostalim/34364-chatham-plaza.yaml
  src/yaml/i-lostalim/34365-corridor-tower.yaml
  src/yaml/i-lostalim/34366-fallbrook-tower.yaml
  src/yaml/i-lostalim/34367-franklin-insurance.yaml
  src/yaml/i-lostalim/34368-hogan-commercial.yaml
  src/yaml/i-lostalim/34369-pacific-way.yaml
  src/yaml/i-lostalim/34370-peachtree-plaza.yaml
  src/yaml/i-lostalim/34371-pentatonic-offices.yaml
  src/yaml/i-lostalim/34372-sapphire-company-offices.yaml
  src/yaml/i-lostalim/34373-tourmaline-residential.yaml
  src/yaml/i-lostalim/34374-valley-paradise-building.yaml
  src/yaml/i-lostalim/34516-tower-plaza.yaml
  src/yaml/i-lostalim/35517-the-rainford.yaml
Labels: package

#61 metadata: add gutterclub's content
  actions/fetch/complete-metadata.js
  actions/fetch/test/integration-test.js
  permissions.yaml
  src/yaml/gutterclub/25665-herbert-building.yaml
  src/yaml/gutterclub/25666-savage-tower.yaml
  src/yaml/gutterclub/25979-telco-building-v2.yaml
  src/yaml/gutterclub/26143-katayama-apartments.yaml
  src/yaml/gutterclub/27119-105-sywell-road.yaml
  src/yaml/gutterclub/27256-96-west-street.yaml
  src/yaml/gutterclub/27492-small-caffe-nero.yaml
  src/yaml/gutterclub/27768-sunrise-house.yaml
  src/yaml/gutterclub/27814-tyler-street-garage.yaml
  src/yaml/gutterclub/27954-topman-menswear.yaml
  src/yaml/gutterclub/27992-generic-cafe-s.yaml
  src/yaml/gutterclub/28035-city-tattoo.yaml
  src/yaml/gutterclub/28151-westpac-on-broadway.yaml
  src/yaml/gutterclub/28179-33-lewis-avenue.yaml
  src/yaml/gutterclub/28368-modern-row-homes.yaml
  src/yaml/gutterclub/28419-aut-student-tower.yaml
  src/yaml/gutterclub/28511-teed-street-larder.yaml
  src/yaml/gutterclub/28727-avon-heights-v2.yaml
  src/yaml/gutterclub/28893-pitt-street-apartments.yaml
  src/yaml/gutterclub/28894-adidas-store.yaml
  src/yaml/gutterclub/29222-innovation-house.yaml
  src/yaml/gutterclub/29739-hobson-rise.yaml
  src/yaml/gutterclub/29984-52-teed-street.yaml
  src/yaml/gutterclub/29985-54-teed-street.yaml
  src/yaml/gutterclub/30902-shaky-isles-coffee-co.yaml
  src/yaml/gutterclub/31259-modern-row-home-4.yaml
  src/yaml/gutterclub/31427-newmarket-crossfit.yaml
  src/yaml/gutterclub/31507-132-teed-street-apartments.yaml
  src/yaml/gutterclub/31566-take-it-or-leave-it-pack.yaml
  src/yaml/gutterclub/31567-hawker-studios.yaml
  src/yaml/gutterclub/32337-sywell-tires.yaml
  src/yaml/gutterclub/32338-jenx-reboots.yaml
  src/yaml/gutterclub/32595-spqr-cafe.yaml
  src/yaml/gutterclub/32699-jetts-fitness.yaml
  src/yaml/gutterclub/32799-richies-electronics.yaml
  src/yaml/gutterclub/33358-goodness-gracious-uptown-bagelry.yaml
  src/yaml/gutterclub/33544-hamilton-fabric.yaml
  src/yaml/gutterclub/33586-42-dickens-road.yaml
  src/yaml/gutterclub/34286-janelle-s-place.yaml
  src/yaml/gutterclub/35393-generic-repairs.yaml
  src/yaml/gutterclub/35915-kodebo-los-angeles-city-hall.yaml
  src/yaml/gutterclub/36439-murray-beer-co.yaml
  src/yaml/simfox/20411-chestnuts.yaml
Labels: package

#81 Add yticmic's content
  src/yaml/yticmic/10935-western-duplex.yaml
  src/yaml/yticmic/10946-aluminium-rowhomes.yaml
  src/yaml/yticmic/10947-titanium-rowhomes.yaml
  src/yaml/yticmic/11278-western-duplex-version-2.yaml
  src/yaml/yticmic/11279-small-wooden-house.yaml
  src/yaml/yticmic/11311-small-lofts.yaml
  src/yaml/yticmic/11312-small-lofts-sandstone.yaml
  src/yaml/yticmic/11319-mcorp-offices.yaml
  src/yaml/yticmic/11332-minicorp-industrials.yaml
  src/yaml/yticmic/12504-stone-terraces-mixed-use.yaml
  src/yaml/yticmic/12513-the-saint-louis.yaml
  src/yaml/yticmic/12516-pizza-hut-express.yaml
  src/yaml/yticmic/12518-mellon-apartments.yaml
  src/yaml/yticmic/12549-the-carbon-building.yaml
  src/yaml/yticmic/12577-deco-incorporated.yaml
  src/yaml/yticmic/12590-mcorp-offices-update.yaml
  src/yaml/yticmic/12591-modern-rowhomes-updated.yaml
  src/yaml/yticmic/12603-small-lofts-updated.yaml
  src/yaml/yticmic/14405-small-theater-pack.yaml
  src/yaml/yticmic/16264-christophers-bar.yaml
  src/yaml/yticmic/16265-corner-shops.yaml
  src/yaml/yticmic/16266-woodstock-candies.yaml
Labels: package

#82 feat: add `--split` flag for splitting packages
  actions/fetch/complete-metadata.js
  actions/fetch/escape-pattern.js
  actions/fetch/fetch-all.js
  actions/fetch/generate-variants.js
  actions/fetch/handle-upload.js
  actions/fetch/split-package.js
  actions/fetch/symbols.js
  actions/fetch/test/expand-variants-test.js
  actions/fetch/test/faker.js
  actions/fetch/test/split-package-test.js
  package-lock.json
  package.json
  scripts/manual-add.js
Labels: feature

#83 metadata: add nbvc's content
  permissions.yaml
  scripts/manual-add.js
  scripts/parse-dependencies.js
  src/yaml/nbvc/23102-plazas-with-fountains.yaml
  src/yaml/nbvc/24528-modular-breakwater-set.yaml
  src/yaml/nbvc/24793-grey-rocks.yaml
  src/yaml/nbvc/24859-bikes.yaml
  src/yaml/nbvc/25621-roundabout-fillers.yaml
  src/yaml/nbvc/26175-riprap-seawall.yaml
  src/yaml/nbvc/26255-riprap-seawall-addon.yaml
  src/yaml/nbvc/26365-modular-oil-port.yaml
  src/yaml/nbvc/26529-rock-clusters.yaml
  src/yaml/nbvc/26574-surfers.yaml
  src/yaml/nbvc/26672-dirty-alleys.yaml
  src/yaml/nbvc/26928-bridge-footing.yaml
  src/yaml/nbvc/27240-logging-set.yaml
  src/yaml/nbvc/27417-tents.yaml
  src/yaml/nbvc/27700-asian-street-market.yaml
  src/yaml/nbvc/27859-high-rocks.yaml
  src/yaml/nbvc/27879-tropical-plants-mmp.yaml
  src/yaml/nbvc/28049-turtles.yaml
  src/yaml/nbvc/28137-driftwood.yaml
  src/yaml/nbvc/28146-divers-and-boats.yaml
  src/yaml/nbvc/28208-sharks.yaml
  src/yaml/nbvc/28225-corals.yaml
  src/yaml/nbvc/28267-fishs-and-rays.yaml
  src/yaml/nbvc/28308-dolphins.yaml
  src/yaml/nbvc/28325-shipwrecks.yaml
  src/yaml/nbvc/28477-sailboats.yaml
  src/yaml/nbvc/28532-garbage-disposal-facilities.yaml
  src/yaml/nbvc/28706-desert-pack.yaml
  src/yaml/nbvc/28879-riprap-seawall-pipes.yaml
  src/yaml/nbvc/28951-marina.yaml
  src/yaml/nbvc/29045-modular-marina-addon.yaml
  src/yaml/nbvc/29498-boats-and-buoys.yaml
  src/yaml/nbvc/29870-marina-round-corners.yaml
Labels: package

#84 metadata: add Seraf's content
  actions/fetch/generate-variants.js
  actions/fetch/scrape.js
  actions/fetch/test/integration-test.js
  permissions.yaml
  src/yaml/jawood/3595-aspen-village-condominiums-multi-color-version.yaml
  src/yaml/jawood/4117-splash-point-water-park-water-slide-tower.yaml
  src/yaml/jawood/4144-splash-point-water-park-wave-pool.yaml
  src/yaml/jawood/4229-splash-point-water-park-front-entrance.yaml
  src/yaml/seraf/23070-new-york-county-supreme-court.yaml
  src/yaml/seraf/23408-michigan-central-station.yaml
  src/yaml/seraf/24300-central-park-cherry-hill-fountain.yaml
  src/yaml/seraf/24323-joseph-pulitzer-fountain.yaml
  src/yaml/seraf/24989-metropolitan-club.yaml
  src/yaml/seraf/25829-alexander-hamilton-u-s-custom-house.yaml
  src/yaml/seraf/26686-elder-park-rotunda.yaml
  src/yaml/seraf/27128-kaiser-wilhelm-nationaldenkmal.yaml
  src/yaml/seraf/28501-jamesfarley-post-office.yaml
  src/yaml/seraf/29856-university-club-of-new-york.yaml
  src/yaml/seraf/29887-city-hall-park-fountain.yaml
  src/yaml/seraf/30206-leaning-tower-of-pisa.yaml
  src/yaml/seraf/30705-new-york-life-insurance-company-annex.yaml
  src/yaml/seraf/30849-hotel-pennsylvania.yaml
  src/yaml/seraf/31865-courthouse-of-the-appellate-division.yaml
  src/yaml/seraf/31866-nos-31-33-madison-avenue.yaml
  src/yaml/seraf/33115-battle-monument-west-point.yaml
  src/yaml/swordmaster/28243-minimize-button-remover.yaml
Labels: package

#85 fix: normalize diacrtics in summary
  actions/fetch/test/api-to-metadata-test.js
  actions/fetch/util.js
Labels: bug

#87 feat: allow specifying packages to be pruned
  scripts/prune.js
Labels: enhancement

#88 deps: bump sc4
  package-lock.json
  package.json
Labels: deps

#89 Bump `sc4`
  package-lock.json
  package.json
Labels: bug, deps

#90 metadata: add a part of Pegasus' content
  actions/fetch/scrape.js
  permissions.yaml
  scripts/prune.js
  scripts/sc4d.js
  scripts/tsc.js
  src/yaml/mrbisonm/11769-nexis-wood-pile-props.yaml
  src/yaml/nbvc/23053-ski-lodge.yaml
  src/yaml/nbvc/23054-fences.yaml
  src/yaml/nbvc/23642-freight-rail-station.yaml
  src/yaml/nbvc/23652-warehouse-dock-outer-corner.yaml
  src/yaml/nbvc/23954-modular-container-port.yaml
  src/yaml/nbvc/25080-water-ploppable-scows.yaml
  src/yaml/nbvc/25531-ski-race.yaml
  src/yaml/nbvc/25532-hut-with-snow.yaml
  src/yaml/nbvc/25596-modular-docks.yaml
  src/yaml/nbvc/26731-tank-car-filling-station.yaml
  src/yaml/nbvc/28532-garbage-disposal-facilities.yaml
  src/yaml/onlyplace4/15246-logging-mill-accomodation.yaml
  src/yaml/onlyplace4/15907-slaytfork-mill-revised.yaml
  src/yaml/paeng/26425-grunge-concrete-set.yaml
  src/yaml/paeng/27284-mtp-logging-addon-vol02.yaml
  src/yaml/peg/11001-trail-parks-iii.yaml
  src/yaml/peg/11065-pine-trails.yaml
  src/yaml/peg/11097-christmas-development-kit.yaml
  src/yaml/peg/11129-refuse-relocation-kit.yaml
  src/yaml/peg/11508-pine-trail-head.yaml
  src/yaml/peg/12426-stream-kit-deluxe-edition.yaml
  src/yaml/peg/14056-mtp-mountain-trails-rec-pack-1.yaml
  src/yaml/peg/14116-mtp-mid-wealth-growable-res-aframes.yaml
  src/yaml/peg/18539-cdk3-fred-ginger-fishery.yaml
  src/yaml/peg/19577-cdk3-sp-container-ship-fleet.yaml
  src/yaml/peg/19805-cdk3-sp-row-warehouses.yaml
  src/yaml/peg/19880-cdk3-super-pak.yaml
  src/yaml/peg/19881-cdk3-sp-seaport-super-pak.yaml
  src/yaml/peg/21053-mtp-logging-roads.yaml
  src/yaml/peg/21072-mtp-tlc-rail-transfer-yard.yaml
  src/yaml/peg/21103-mtp-ltusa-container-generator.yaml
  src/yaml/peg/21147-mtp-ltusa-cross-roads.yaml
  src/yaml/peg/22893-ppond-scows.yaml
  src/yaml/peg/22925-snow-mod-2.yaml
  src/yaml/peg/22995-ski-resort.yaml
  src/yaml/peg/23018-ski-resort-half-way-hut.yaml
  src/yaml/peg/23131-ski-resort-ski-rentals.yaml
  src/yaml/peg/30680-mtp-mountain-trails.yaml
  src/yaml/peg/30681-mtp-parking-lots.yaml
  src/yaml/sg/15402-container-freight-yards.yaml
  src/yaml/simmer2/31129-rail-service-yard-1.yaml
  src/yaml/train-prop-pack-sd.yaml
Labels: package

#91 deps: bump `sc4`
  package-lock.json
  package.json
Labels: deps

#92 metadata: add Parisian's content
  permissions.yaml
  src/yaml/parisian/24915-morgan-court-sliver-building-v1.yaml
  src/yaml/parisian/24924-the-w-times-square.yaml
  src/yaml/parisian/27264-paramount-appartments-tower.yaml
  src/yaml/parisian/27654-cartier-versace-stores-fifth-ave.yaml
  src/yaml/parisian/27689-louis-vuitton-fifth-ave.yaml
  src/yaml/parisian/28496-gotham-style-monumental-lights.yaml
  src/yaml/parisian/28497-ed-koch-queensboro-bridge-1909-lamppost.yaml
  src/yaml/parisian/28616-712-fifth-avenue.yaml
  src/yaml/parisian/28661-the-four-seasons-hotel-tower.yaml
  src/yaml/parisian/30022-tudor-city-tudor-tower.yaml
  src/yaml/parisian/30023-tudor-city-prospect-tower.yaml
  src/yaml/parisian/30025-tudor-city-windsor-tower.yaml
  src/yaml/parisian/31429-the-crown-building-new-york.yaml
  src/yaml/parisian/32012-the-tudor-city-new-york.yaml
  src/yaml/parisian/35233-morgan-court-sliver-building.yaml
Labels: package

#93 feat: add `npm run list` script
  package.json
  scripts/list-dependencies.js
Labels: feature

#94 fix: don't generate links without websites
  scripts/list-dependencies.js
Labels: bug

#95 metadata: add `homer2:beach-set`
  src/yaml/gizmo-vehicle-props.yaml
  src/yaml/homer2/11541-beach-set.yaml
  src/yaml/train-prop-pack-sd.yaml
Labels: package

#96 fix: add variants to `peg:refuse-relocation-kit`
  src/yaml/peg/11129-refuse-relocation-kit.yaml
  src/yaml/peg/11210-alley-kit.yaml
Labels: bug, package

#98 feat: list dependencies for multiple packages
  scripts/list-dependencies.js
Labels: feature

#97 metadata: add dk1's content
  actions/fetch/scrape.js
  permissions.yaml
  src/yaml/dk1/18148-dillards.yaml
  src/yaml/dk1/18209-xoomer-garage-and-gas.yaml
  src/yaml/dk1/18238-library.yaml
  src/yaml/dk1/18280-school-house.yaml
  src/yaml/dk1/18335-monroe-place.yaml
  src/yaml/dk1/18475-highway-patrol-v2.yaml
  src/yaml/dk1/18523-marienkirche-v2.yaml
  src/yaml/dk1/18560-simcity-pallet-co.yaml
  src/yaml/dk1/18605-simcity-medical.yaml
  src/yaml/dk1/18799-railroad-depot.yaml
  src/yaml/dk1/19007-luhrs-tower.yaml
  src/yaml/dk1/19247-macys.yaml
  src/yaml/dk1/19251-bank-of-america.yaml
  src/yaml/dk1/19275-jcpenney.yaml
  src/yaml/dk1/19296-methane-power-plant.yaml
  src/yaml/dk1/19344-convenience-stores.yaml
  src/yaml/dk1/19381-diners.yaml
  src/yaml/dk1/19408-convenience-stores-2.yaml
  src/yaml/dk1/19462-industrial.yaml
  src/yaml/dk1/19482-small-stores.yaml
  src/yaml/dk1/19520-gas-stations.yaml
  src/yaml/dk1/19673-simcity-mall.yaml
  src/yaml/dk1/19745-police-department.yaml
  src/yaml/dk1/19760-freight-station.yaml
  src/yaml/dk1/19827-fire-station.yaml
  src/yaml/dk1/19861-grusom-casket-co.yaml
  src/yaml/dk1/20093-grain-elevator.yaml
  src/yaml/dk1/20157-fence-co.yaml
  src/yaml/dk1/20212-gas-stations-2.yaml
  src/yaml/dk1/20299-burger-chef.yaml
  src/yaml/dk1/20361-small-industrial.yaml
  src/yaml/dk1/20402-freight-station-2.yaml
  src/yaml/dk1/20478-small-church.yaml
  src/yaml/dk1/20557-diners-2.yaml
  src/yaml/dk1/20611-tsbd-building.yaml
  src/yaml/dk1/20631-mcsorleys.yaml
  src/yaml/dk1/20678-retro-kroger.yaml
  src/yaml/dk1/20777-suttons.yaml
  src/yaml/dk1/20867-quiznos-sub.yaml
  src/yaml/dk1/20874-small-restaurant.yaml
  src/yaml/dk1/20951-deli.yaml
  src/yaml/dk1/21031-public-safety.yaml
  src/yaml/dk1/21144-donut-shops.yaml
  src/yaml/dk1/21495-fire-station-3.yaml
  src/yaml/dk1/21504-bowling.yaml
  src/yaml/dk1/21535-diners-3.yaml
  src/yaml/dk1/21609-king-and-queen.yaml
  src/yaml/dk1/22535-power-plant.yaml
  src/yaml/dk1/25597-fast-food.yaml
  src/yaml/dk1/27035-peterson-tool.yaml
Labels: package

#100 metadata: add various packages
  src/yaml/coultharda/18685-small-athletics-and-football-ground.yaml
  src/yaml/coultharda/33707-velodrome.yaml
  src/yaml/nybt/29381-nybt-cbu-fdny-1st-pack.yaml
  src/yaml/peg/12329-pond-kit-ii-deluxe-edition.yaml
  src/yaml/warrior/23771-raise-the-ui-mod.yaml
Labels: package

#101 feat: send DM on Simtropolis after package is published or failed to publish
  .github/workflows/add-packages.yaml
  README.md
  actions/create-prs/action.yaml
  actions/create-prs/create-prs.js
  actions/create-prs/package-publish-failed.md
  actions/create-prs/package-published.md
  actions/send-dm/action.yaml
  actions/send-dm/send-message.js
  actions/send-dm/send-messages.js
  package-lock.json
  package.json
Labels: feature

#106 feat: don't replace apostrophes with hyphens
  actions/fetch/test/api-to-metadata-test.js
  actions/fetch/test/integration-test.js
  actions/fetch/util.js
Labels: enhancement

#56 feat: scaffold basic browser extension
  extensions/build/build.js
  extensions/src/background.js
  extensions/src/copy.js
  extensions/src/icon-128-disabled.png
  extensions/src/icon-128.png
  extensions/src/icon-44-disabled.png
  extensions/src/icon-44.png
  extensions/src/manifest.json
  extensions/src/polyfill.js
  extensions/src/setup.js
  extensions/src/stex.js
  package-lock.json
  package.json
Labels: feature

#107 fix: use package-scoped variant name for resolution
  actions/fetch/generate-variants.js
  actions/fetch/test/expand-variants-test.js
  src/yaml/jasoncw/30410-big-red-lighthouse.yaml
  src/yaml/jasoncw/32737-guardian-building.yaml
Labels: enhancement

#109 feat: allow additional standard dependencies in `.env`
  scripts/sc4pac.js
  scripts/standard-deps.js
  scripts/standard-variants.js
Labels: feature

#110 Add odainsaker's content
  src/yaml/odainsaker/16648-tower-life-building.yaml
  src/yaml/odainsaker/18706-casino-club.yaml
  src/yaml/odainsaker/19227-tower-of-the-americas.yaml
  src/yaml/odainsaker/20076-alexander-column.yaml
  src/yaml/odainsaker/20103-alexander-column-roundabouts.yaml
  src/yaml/odainsaker/20775-broadway-mansions.yaml
  src/yaml/odainsaker/24036-vogue-department-store.yaml
Labels: package

#114 fix: don't introduce empty dependencies when no `STANDARD_DEPENDENCIES` env variable is found
  scripts/standard-deps.js
Labels: bug

#115 metadata: add `cogeo:landfill-eraser-mod`
  src/yaml/cogeo/22737-landfill-eraser-mod.yaml
Labels: package

#117 fix: fix `hhw-freightliner` package name
  src/yaml/pclark06/32671-hhw-freightliner.yaml
  src/yaml/pclark06/33838-international-trucks-dealer.yaml
Labels: bug, package

#112 Add Vlasky's content
  src/yaml/vlasky/22203-red-resident.yaml
  src/yaml/vlasky/22639-tour-de-arc.yaml
  src/yaml/vlasky/23212-super-green.yaml
  src/yaml/vlasky/28271-525-west-48th-street.yaml
  src/yaml/vlasky/28537-todds-packaging-plant.yaml
  src/yaml/vlasky/28583-midtown-theater.yaml
  src/yaml/vlasky/29091-maritime-exchange-building.yaml
  src/yaml/vlasky/29129-diagonal-maritime-exchange-building.yaml
Labels: package

#102 docs: improve documentation for launch
  README.md
Labels: enhancement

#119 metadata: add Coultharda's content
  src/yaml/coultharda/14159-5aside-football-centre.yaml
  src/yaml/coultharda/15023-dover-road-moneyfields-fc.yaml
  src/yaml/coultharda/15171-victory-stadium.yaml
  src/yaml/coultharda/15493-ill-tonkso-stadium.yaml
  src/yaml/coultharda/15538-nuffield-stadium.yaml
  src/yaml/coultharda/15909-all-weather-pitch.yaml
  src/yaml/coultharda/16551-ill-tonkso-park-v2.yaml
  src/yaml/coultharda/16738-dixon-kennedy-stadium.yaml
  src/yaml/coultharda/16868-sobcitski-stadium.yaml
  src/yaml/coultharda/17505-freya-park.yaml
  src/yaml/coultharda/17585-generic-modern-uk-stadium.yaml
  src/yaml/coultharda/17921-small-football-ground.yaml
  src/yaml/coultharda/18016-small-football-ground-2.yaml
  src/yaml/coultharda/18023-david-collett-stadium.yaml
  src/yaml/coultharda/18045-small-football-ground-3.yaml
  src/yaml/coultharda/18153-river-park-stadium.yaml
  src/yaml/coultharda/18641-small-football-ground-4.yaml
  src/yaml/coultharda/25507-all-weather-hockey-and-football-pitch.yaml
  src/yaml/coultharda/33690-small-football-ground-5.yaml
  src/yaml/coultharda/33692-small-rugby-stadium.yaml
  src/yaml/coultharda/33696-small-football-stadium.yaml
Labels: package

#120 metadata: add `gamzdude:radical-rci-demand-mod`
  src/yaml/gamzdude/26720-radical-rci-demand-graph-mod.yaml
Labels: package

#122 feat: support `--darknite-only` flag
  actions/fetch/api-to-metadata.js
  actions/fetch/fetch-all.js
  scripts/manual-add.js
Labels: enhancement

#123 fix: remove MML from MAPP
  src/yaml/aldara6166/17557-modular-amusement-park-pack-essentials.yaml
Labels: bug, package

#126 metadata: add `mgb204:mmp-pack-vol2`
  permissions.yaml
  scripts/sc4d.js
  src/yaml/mgb204/31285-mmp-pack-vol2.yaml
Labels: package
