Repository sebamarynissen/simtropolis-channel, pull requests merged in 2025-04, with the labels that each got.

#195 feat: add support for `.rar` and `.7z` archives
  .github/workflows/add-packages.yaml
  README.md
  actions/fetch/downloader.js
  actions/fetch/test/integration-test.js
  package-lock.json
  package.json
Labels: feature, actions

#196 metadata: add missing wannglondon content
  src/yaml/wannglondon/36213-medit-bldg-59.yaml
  src/yaml/wannglondon/36671-los-angeles-home-5.yaml
  src/yaml/wannglondon/36762-american-shops-pack-1.yaml
  src/yaml/wannglondon/36768-california-bungalow-pack.yaml
  src/yaml/wannglondon/36814-los-angeles-home-7.yaml
Labels: package

#197 fix: use sc4pac user agent
  actions/fetch/downloader.js
Labels: bug

#198 metadata: add traffic generating lots
  src/yaml/meinhosen/17000-american-traffic-generating-lots.yaml
  src/yaml/mikeseith/14400-european-cars-automata-and-family-props-new-instances.yaml
  src/yaml/mikeseith/16257-euro-traffic-generator.yaml
Labels: package

#184 Add Aarsgevogelte's content
  src/yaml/aarsgevogelte/30914-dinghuis-maastricht.yaml
  src/yaml/aarsgevogelte/30924-yellow-house-rotterdam.yaml
  src/yaml/aarsgevogelte/30935-european-w2w-building.yaml
  src/yaml/aarsgevogelte/30980-victoria-hotel-amsterdam.yaml
  src/yaml/aarsgevogelte/31367-european-corner-building.yaml
  src/yaml/aarsgevogelte/31371-stationsweg-26-s-hertogenbosch.yaml
  src/yaml/aarsgevogelte/31386-european-w2w-building.yaml
  src/yaml/aarsgevogelte/31393-modepaleis-antwerpen.yaml
  src/yaml/aarsgevogelte/31395-zuidkasteel-antwerpen.yaml
  src/yaml/aarsgevogelte/31400-volkshuis-gent.yaml
  src/yaml/aarsgevogelte/31406-heuvelstraat-109-and-stationsstraat-41-tilburg.yaml
  src/yaml/aarsgevogelte/31407-damrak-60-and-62-amsterdam.yaml
  src/yaml/aarsgevogelte/32112-stationsstraat-45-tilburg.yaml
  src/yaml/aarsgevogelte/32115-stationsweg-33-s-hertogenbosch.yaml
  src/yaml/aarsgevogelte/32116-stationsplein-3-s-hertogenbosch.yaml
  src/yaml/aarsgevogelte/32118-colignonplein-1-brussel.yaml
  src/yaml/aarsgevogelte/32120-tuinstraat-72-74-tilburg.yaml
  src/yaml/aarsgevogelte/32121-kloveniersburgwal-87-amsterdam.yaml
  src/yaml/aarsgevogelte/32122-stationsstraat-25-tilburg.yaml
  src/yaml/aarsgevogelte/32123-cafe-bauer-leipzig.yaml
  src/yaml/aarsgevogelte/32128-cinecitta-tilburg.yaml
  src/yaml/aarsgevogelte/32129-grote-markt-6-sint-niklaas.yaml
  src/yaml/aarsgevogelte/32130-spoorlaan-386-tilburg.yaml
  src/yaml/aarsgevogelte/32131-nieuwlandstraat-28-30-32-tilburg.yaml
  src/yaml/aarsgevogelte/32132-leliegracht-25-amsterdam.yaml
  src/yaml/aarsgevogelte/32133-stationsstraat-32-tilburg.yaml
  src/yaml/aarsgevogelte/32136-wilsonova-3-prague.yaml
  src/yaml/aarsgevogelte/32141-snellenlaan-108-utrecht.yaml
  src/yaml/aarsgevogelte/32143-victoria-hotel-amsterdam.yaml
  src/yaml/aarsgevogelte/33593-elberg-eiloo.yaml
  src/yaml/aarsgevogelte/33596-eagle-star-antwerp.yaml
Labels: package

#201 metadata: add recent ids2 packages
  src/yaml/ids2/36778-tj-maxx-and-homegoods.yaml
  src/yaml/ids2/36780-lalumiere-hall.yaml
  src/yaml/ids2/36800-equitable-building.yaml
Labels: package

#203 metadata: add Simcoug's content
  permissions.yaml
  scripts/sc4d.js
  src/yaml/delija21/21560-ruins.yaml
  src/yaml/evilcoolkid/20065-ww2-destroyed-buildings-v1.yaml
  src/yaml/evilcoolkid/20073-ww2-destroyed-buildings-v2.yaml
  src/yaml/johnb/3345-totem-pole.yaml
  src/yaml/peg/19362-cdk3-coast-guard-station.yaml
  src/yaml/simcoug/28307-maxis-rss-homes.yaml
  src/yaml/simcoug/28426-old-rs-neighborhoods.yaml
  src/yaml/simcoug/28630-rss-diagonal-homes.yaml
  src/yaml/simcoug/28957-peg-coast-guard-boats.yaml
  src/yaml/simcoug/29000-diagonal-w2w-tenements.yaml
  src/yaml/simcoug/30425-stairways.yaml
  src/yaml/simcoug/30688-cp-lodgepole-fence-mmp.yaml
  src/yaml/simcoug/30690-ruins-mmp.yaml
  src/yaml/simcoug/30807-semi-truck-cabs-vol1-mmp.yaml
  src/yaml/simcoug/30869-american-indian-prop-mmp.yaml
  src/yaml/simcoug/31753-little-well.yaml
  src/yaml/simcoug/31771-mattb325s-historic-shops.yaml
Labels: package

#204 metadata: fix MN/DN in `simcoug:mattb325-historic-shops`
  src/yaml/simcoug/28157-cemetery-props-mmp.yaml
  src/yaml/simcoug/31771-mattb325s-historic-shops.yaml
Labels: package
